import React from "react";
import {
  Brain,
  Sparkles,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  Lightbulb,
  Target,
  Activity,
} from "lucide-react";

const insights = [
  {
    title: "Demand Growth Prediction",
    description:
      "AI forecasts a 24.5% increase in demand during the next quarter.",
    type: "positive",
    icon: TrendingUp,
  },
  {
    title: "Inventory Optimization",
    description:
      "Increase inventory allocation by 18% to prevent stock shortages.",
    type: "recommendation",
    icon: Target,
  },
  {
    title: "Forecast Accuracy Improvement",
    description:
      "Latest retrained model improved forecasting accuracy to 96.8%.",
    type: "positive",
    icon: Brain,
  },
  {
    title: "Demand Volatility Alert",
    description:
      "Product Category B shows higher-than-normal volatility.",
    type: "warning",
    icon: AlertTriangle,
  },
  {
    title: "Revenue Opportunity",
    description:
      "Premium products expected to generate additional revenue growth.",
    type: "recommendation",
    icon: Lightbulb,
  },
];

const getInsightStyles = (type) => {
  switch (type) {
    case "positive":
      return {
        bg: "bg-green-50",
        icon: "text-green-600",
        badge: "bg-green-100 text-green-700",
        label: "Positive",
      };

    case "warning":
      return {
        bg: "bg-red-50",
        icon: "text-red-600",
        badge: "bg-red-100 text-red-700",
        label: "Warning",
      };

    default:
      return {
        bg: "bg-blue-50",
        icon: "text-blue-600",
        badge: "bg-blue-100 text-blue-700",
        label: "Recommendation",
      };
  }
};

const AIInsights = () => {
  return (
    <div className="space-y-4">

      {/* Header */}

      <div
        className="
          bg-white
          rounded-2xl
          border
          border-slate-200
          p-5
          shadow-sm
        "
      >
        <div className="flex items-center gap-3">

          <Brain
            size={28}
            className="text-blue-600"
          />

          <div>
            <h2 className="text-xl font-bold text-slate-900">
              AI Insights Center
            </h2>

            <p className="text-sm text-slate-500 mt-1">
              Machine learning intelligence and forecasting recommendations
            </p>
          </div>

        </div>
      </div>

      {/* KPI Cards */}

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">

        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
          <Brain
            size={24}
            className="text-blue-600"
          />

          <p className="text-sm text-slate-500 mt-3">
            AI Accuracy
          </p>

          <h3 className="text-3xl font-bold mt-2">
            96.8%
          </h3>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
          <TrendingUp
            size={24}
            className="text-green-600"
          />

          <p className="text-sm text-slate-500 mt-3">
            Demand Growth
          </p>

          <h3 className="text-3xl font-bold mt-2">
            +24.5%
          </h3>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
          <Activity
            size={24}
            className="text-purple-600"
          />

          <p className="text-sm text-slate-500 mt-3">
            AI Confidence
          </p>

          <h3 className="text-3xl font-bold mt-2">
            98.1%
          </h3>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
          <Sparkles
            size={24}
            className="text-cyan-600"
          />

          <p className="text-sm text-slate-500 mt-3">
            Active Insights
          </p>

          <h3 className="text-3xl font-bold mt-2">
            42
          </h3>
        </div>

      </div>

      {/* Insights Feed */}

      <div
        className="
          bg-white
          rounded-2xl
          border
          border-slate-200
          shadow-sm
        "
      >
        <div className="p-5 border-b border-slate-100">

          <h3 className="text-lg font-semibold">
            AI Recommendations
          </h3>

          <p className="text-sm text-slate-500">
            Latest forecasting intelligence generated by AI
          </p>

        </div>

        <div className="p-5 space-y-4">

          {insights.map((item, index) => {
            const Icon = item.icon;
            const styles = getInsightStyles(item.type);

            return (
              <div
                key={index}
                className={`
                  p-5
                  rounded-2xl
                  border
                  border-slate-200
                  ${styles.bg}
                `}
              >
                <div className="flex gap-4">

                  <div
                    className="
                      h-12
                      w-12
                      rounded-xl
                      bg-white
                      flex
                      items-center
                      justify-center
                    "
                  >
                    <Icon
                      size={22}
                      className={styles.icon}
                    />
                  </div>

                  <div className="flex-1">

                    <div className="flex items-center justify-between">

                      <h4 className="font-semibold text-slate-900">
                        {item.title}
                      </h4>

                      <span
                        className={`
                          px-3
                          py-1
                          rounded-full
                          text-xs
                          font-semibold
                          ${styles.badge}
                        `}
                      >
                        {styles.label}
                      </span>

                    </div>

                    <p className="text-slate-600 mt-3">
                      {item.description}
                    </p>

                  </div>

                </div>
              </div>
            );
          })}

        </div>
      </div>

      {/* Executive AI Intelligence */}

      <div
        className="
          rounded-2xl
          bg-gradient-to-r
          from-slate-950
          via-blue-950
          to-slate-950
          p-6
          text-white
        "
      >
        <div className="flex items-center gap-3 mb-5">

          <Sparkles size={22} />

          <h3 className="text-xl font-bold">
            Executive AI Intelligence
          </h3>

        </div>

        <div className="grid md:grid-cols-3 gap-6">

          <div>
            <h4 className="text-cyan-300 font-semibold">
              Demand Forecast
            </h4>

            <p className="text-slate-300 mt-2">
              Growth trajectory remains strong across strategic product lines.
            </p>
          </div>

          <div>
            <h4 className="text-green-300 font-semibold">
              Revenue Outlook
            </h4>

            <p className="text-slate-300 mt-2">
              Revenue projections exceed quarterly business objectives.
            </p>
          </div>

          <div>
            <h4 className="text-yellow-300 font-semibold">
              AI Recommendation
            </h4>

            <p className="text-slate-300 mt-2">
              Continue automated retraining and inventory optimization.
            </p>
          </div>

        </div>
      </div>

    </div>
  );
};

export default AIInsights;